swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport: smtp
    auth_mode:  login
    host:       ssl0.ovh.net
    port:       587
    username: admin@ckngf.fr
    password: admin12345
