<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mission extends \App\Entity\Mission implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'missionTitle', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'missionText', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'getPlayer'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'missionTitle', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'missionText', '' . "\0" . 'App\\Entity\\Mission' . "\0" . 'getPlayer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mission $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionTitle', []);

        return parent::getMissionTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionTitle(string $missionTitle): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionTitle', [$missionTitle]);

        return parent::setMissionTitle($missionTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getMissionText(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMissionText', []);

        return parent::getMissionText();
    }

    /**
     * {@inheritDoc}
     */
    public function setMissionText(string $missionText): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMissionText', [$missionText]);

        return parent::setMissionText($missionText);
    }

    /**
     * {@inheritDoc}
     */
    public function getGetPlayer(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGetPlayer', []);

        return parent::getGetPlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function addGetPlayer(\App\Entity\Participant $getPlayer): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGetPlayer', [$getPlayer]);

        return parent::addGetPlayer($getPlayer);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGetPlayer(\App\Entity\Participant $getPlayer): \App\Entity\Mission
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGetPlayer', [$getPlayer]);

        return parent::removeGetPlayer($getPlayer);
    }

}
