<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSGs0Xtm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSGs0Xtm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSGs0Xtm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSGs0Xtm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSGs0Xtm\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SGs0Xtm',
    'container.build_id' => '1473c619',
    'container.build_time' => 1540047869,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSGs0Xtm');
