<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFf5hUPh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFf5hUPh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFf5hUPh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFf5hUPh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerFf5hUPh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ff5hUPh',
    'container.build_id' => '2f3c9af9',
    'container.build_time' => 1540042572,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFf5hUPh');
